sudo: required
services:
  - docker

before_install:
  - docker build -t mkadmin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mkadmin/react-test npm test -- --coverage

after_success:
  - docker build -t dotski/multi-client ./client
  - docker build -t dotski/multi-server ./server
  - docker build -t dotski/multi-nginx ./nginx
  - docker build -t dotski/multi-worker ./worker
  # Log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push dotski/multi-client
  - docker push dotski/multi-server
  - docker push dotski/multi-nginx
  - docker push dotski/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-288653573408"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
